### ISSUE TITLE
wdpar requires a chromium installation

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/interactive-deforestation-map#1]
When running non-interactivley on a server I see:

```
`google-chrome` and `chromium-browser` were not found. Try setting the `CHROMOTE_CHROME` environment variable to the executable of a Chromium-based browser, such as Google Chrome, Chromium or Brave or adding one of these executables to your PATH.
Error: couldn't find a Chromium-based browser,please try installing Google Chrome
```

This is caused by `wdpar::wdpa_fetch()`. Not sure if I like the idea requiring users of this script to have chromium browser installed. Do we have other ideas for a lightweight solution to fetch single WDPAs?

**Comment by karpfen** [comment]
I think there's two alternatives for the wdpar package:
1. API: Would be ideal IMO, because with it we only need to download what we actually need for the map. Plus the user can just define WDPA ids and doesn't have to manually select the Country as well.
But then every user needs API keys, so I'd not go that way.

2. Dump the whole WDPA db: This would work well in principle, but causes a silly amount of overhead and potential errors if users have to do all preprocessing on their machines.

So for now, I'd go with the lame answer: we use `wdpar`, which depends on chromium, therefore chromium is a transient dependency for us.

**Comment by goergen95** [comment]
Another option would be to directly query from the latest source, but this is not very performant because the data is not cloud-optimized...

```r
library(sf)

fetch_wdpaid <- function(id) {

  baseurl <- "https://pp-import-production.s3-eu-west-1.amazonaws.com/WDPA_WDOECM_%s_Public.zip"
  latest <- basename(httr::HEAD("http://wcmc.io/wdpa_current_release")$url)[[1]]
  latest <- strsplit(latest, "_")[[1]][3]

  url <- file.path("/vsizip", "/vsicurl", sprintf(baseurl, latest))
  gdb <- sprintf("WDPA_WDOECM_%s_Public.gdb", latest)
  url <- file.path(url, gdb)

  layer <-  grep("poly", sf::st_layers(url)[["name"]], value = TRUE)
  query <- "select * from %s where WDPAID = %s"
  query <- sprintf(query, layer, id)

  st_read(url, query = query)

}
```

**Comment by goergen95** [comment]
~How about the ArcGIS REST server? Currently its only fetching the geometry and is missing the metadata, but that seems to work:~

*Edit*: Now it also returns the metadata:
*Edit2*: Even shorter :laughing: 

```r
fetch_wdpaid <- function(id) {

  url <- "https://data-gis.unep-wcmc.org/server/rest/services/ProtectedSites/The_World_Database_of_Protected_Areas/FeatureServer/1/query?where=WDPAID+=+%s&geometryType=esriGeometryPolygon&outFields=*&f=geojson"
  st_read(sprintf(url, id))

}
```
